### ISSUE TITLE
[BUG] Mermaid graph labels are truncated when bold

### ISSUE THREAD

**Issue by Sasparle** [JeffDess/redmine-kroki#4]
**Describe the bug**
Voir la balise `subgraph OE[<b>Ordinateur Écrivain</b>]`, l'ajout de <b> fait que le texte dépasse de sa zone d'affichage.

**To Reproduce**
Exemple de mermaid 

{{kroki(mermaid)
graph

subgraph OE[<b>Beau titre</b>]

end
}}

**Screenshots**
![image](https://github.com/user-attachments/assets/4bfb9b25-bb9c-426c-a890-e330b0cb7d33)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Safari

**Comment by JeffDess** [comment]
It was also affecting regular labels, not just titles.
I fixed just those specific cases as I do not wish to mess up the Mermaid rendering too much. There might be other instances of this bug in other types of charts. Please report if you encounter this again.

Will be fixed in next release @Sasparle, thanks!
